name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build
